### ISSUE TITLE
HOG-05C: Potential Significant Utility Optimization

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-labs/data-structures#36]
## HOG-05C: Potential Significant Utility Optimization

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Gas Optimization](/appendix/finding-types#gas-optimization) | <img class="o-severity o-informational" src="https://omniscia.io/report-assets/informational.png" /> | [HeapOrdering.sol:L4](https://github.com/morpho-labs/data-structures/blob/6b3f07abe798c6e4378f80bee76db6b8f3a44ed1/contracts/HeapOrdering.sol#L4) |

### Description:

The heap data structure implemented by the library is usually utilized to implement priority queues and other similar mechanisms where a common use case is to "pop" the upper-most parent of the "queue" and insert a new item that should be queued for the next iteration. If this is an envisioned use case for the heap, a significant utility and gas optimization can be achieved by implementing a dedicated "replace" function that replaces the root of the tree and then ascertains order by performing a single `shiftDown` operation.

### Example:

```solidity
library HeapOrdering {
```

### Recommendation:

We advise this use-case to be evaluated and the function described to be implemented in case it is envisioned as frequent given that it will lead to significant gas optimizations.

**Comment by QGarchery** [comment]
This is a nice idea, and we already do those kind of optimization (with `increase`/`decrease`). But in our case I don't think it is really useful because it is difficult to know wether an other account will replace the one we remove before doing all the matching.

I would add this to the "pure" heap data structure, and close this issue for now. What do you think @MerlinEgalite @MathisGD ?

**Comment by MathisGD** [comment]
For a general purpose heap, yes it seems to be a good idea. But for the heap used for Morpho, because we are not going to use it, I would not implement it.
