### ISSUE TITLE
HOG-02S: Repetitive Value Literal

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-labs/data-structures#41]
## HOG-02S: Repetitive Value Literal

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Code Style](/appendix/finding-types#code-style) | <img class="o-severity o-informational" src="https://omniscia.io/report-assets/informational.png" /> | [HeapOrdering.sol:L128](https://github.com/morpho-labs/data-structures/blob/6b3f07abe798c6e4378f80bee76db6b8f3a44ed1/contracts/HeapOrdering.sol#L128), [L285](https://github.com/morpho-labs/data-structures/blob/6b3f07abe798c6e4378f80bee76db6b8f3a44ed1/contracts/HeapOrdering.sol#L285), [L304](https://github.com/morpho-labs/data-structures/blob/6b3f07abe798c6e4378f80bee76db6b8f3a44ed1/contracts/HeapOrdering.sol#L304) |

### Description:

The linked literal `1` is utilized in the linked portions to signify the head of the heap array, i.e. the root of the heap tree.

### Example:

```solidity
/// @notice Returns the address coming before `_id` in accounts.
/// @dev The account associated to the returned address does not necessarily have a lower value than the one of the account associated to `_id`.
/// @param _heap The heap to search in.
/// @param _id The address of the account.
/// @return The address of the previous account.
function getPrev(HeapArray storage _heap, address _id) internal view returns (address) {
    uint256 rank = _heap.ranks[_id];
    if (rank > 1) return getAccount(_heap, rank - 1).id;
    else return address(0);
}
```

### Recommendation:

We advise this to be better illustrated by setting a contract-level `constant` declaration (i.e. `HEAP_ROOT`) in which the value of `1` is stored greatly improving the legibility of the codebase. To note, in the first linked line only the first instance of `1` should be replaced as the latter instance is a binary offset.

**Comment by MathisGD** [comment]
what do you think about this one @QGarchery ?

**Comment by QGarchery** [comment]
It is used in 2 places I believe. It adds some clarity and costs nothing so I like it. I think `ROOT_RANK` describes this variable more accurately

**Comment by MathisGD** [comment]
It also makes sense to use them here. Not sure if we want that or not 🤔 

<img width="578" alt="Capture d’écran 2022-07-06 à 10 20 02" src="https://user-images.githubusercontent.com/74971347/177504379-77010a3b-19d6-4771-9507-62e967c8fb0a.png">
