### ISSUE TITLE
HOG-01M: Potentially Ambiguous Functionality

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-labs/data-structures#42]
## HOG-01M: Potentially Ambiguous Functionality

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Standard Conformity](/appendix/finding-types#standard-conformity) | <img class="o-severity o-unknown" src="https://omniscia.io/report-assets/unknown.png" /> | [HeapOrdering.sol:L289-L295](https://github.com/morpho-labs/data-structures/blob/6b3f07abe798c6e4378f80bee76db6b8f3a44ed1/contracts/HeapOrdering.sol#L289-L295) |

### Description:

The `getTail` function yields the tail of the overall account array rather than the tail of the sorted heap array which can cause mis-use by the library's users.

### Example:

```solidity
/// @notice Returns the address at the tail of the `_heap`.
/// @param _heap The heap to get the tail.
/// @return The address of the tail.
function getTail(HeapArray storage _heap) internal view returns (address) {
    if (_heap.accounts.length > 0) return getAccount(_heap, _heap.accounts.length).id;
    else return address(0);
}
```

### Recommendation:

We advise a separate, dedicated `getHeapTail` function to be introduced that yields the ordered tree portion's tail member to its caller, increasing the utility of the library.

**Comment by MathisGD** [comment]
We are not going to implement the getHeapTail function, because this heap is not for general purpose.
