### ISSUE TITLE
HOG-02M: Inexistent Association of Former Value

### ISSUE THREAD

**Issue by QGarchery** [morpho-labs/data-structures#43]
## HOG-02M: Inexistent Association of Former Value

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Input Sanitization](/appendix/finding-types#input-sanitization) | <img class="o-severity o-minor" src="https://omniscia.io/report-assets/minor.png" /> | [HeapOrdering.sol:L30-L36](https://github.com/morpho-labs/data-structures/blob/6b3f07abe798c6e4378f80bee76db6b8f3a44ed1/contracts/HeapOrdering.sol#L30-L36) |

### Description:

The `_formerValue` argument is meant to indicate the current value of the particular `_id` in the heap structure, however, this is not validated and is instead assumed to be trusted input.

### Impact:

An improper `_formerValue` combined with an improper `_newValue` will cause an incorrect operation to be performed on the heap that does not match the actual data the `_id` entry previously held.

### Example:

```solidity
function update(
    HeapArray storage _heap,
    address _id,
    uint256 _formerValue,
    uint256 _newValue,
    uint256 _maxSortedUsers
) internal {
    uint256 size = _heap.size;
    uint256 newSize = computeSize(size, _maxSortedUsers);
    if (size != newSize) _heap.size = newSize;

    if (_formerValue != _newValue) {
        if (_newValue == 0) remove(_heap, _id, _formerValue);
        else if (_formerValue == 0) insert(_heap, _id, _newValue, _maxSortedUsers);
        else if (_formerValue < _newValue) increase(_heap, _id, _newValue, _maxSortedUsers);
        else decrease(_heap, _id, _newValue);
    }
}
```

### Recommendation:

While the contract is a `library` and thus input sanitization can be performed at the application level, from a security standpoint this reliance is ill-advised. Instead, we advise the `_formerValue` to be queried directly on the heap structure to guarantee all operations are performed safely regardless of end-user usage. If gas optimization is a concern here (as the data entry is already read by the caller), we advise a delta system to be used instead (i.e. specifying a decrease as `-5`) which would optimize the `if` conditionals and allow the entry to be read once at the heap level.

**Comment by QGarchery** [comment]
The delta solution, just like loading the `_formerValue`, leads to one more (warm) load operation. Should we implement it to make sure the library is used as intended ?

**Comment by MathisGD** [comment]
It seems that there is no way to implement this without adding gas cost. The purpose of this heap is to be used in Morpho only, and Morpho should always use the good inputs. 

But for a general purpose OS heap, yes it is an important check to do.

**Comment by MerlinEgalite** [comment]
did you check the delta solution?

**Comment by QGarchery** [comment]
No and I'm not sure how it is possible to implement it so that the `if` statements are cheaper: either have an `int` instead of a `uint` or we need another boolean value indicating if the delta is positive or negative. Both solutions don't seem satisfactory, what do you think ?

Also, it does not solve the main issue: we are adding a warm SLOAD.

So I did the change where we add a load at every updatecall, but the result in gas can't be conclusive, because the test already did the load too (see branch `refactor/update-gets-former-value` for the implementation).
